output "api_gateway_prod_url" {
  description = "Base URL for API Gateway stage."

  value = aws_apigatewayv2_stage.prod.invoke_url
}

output "lambda_dummy_function_name" {
  value = module.lambda_dummy.function_name
}

resource "local_sensitive_file" "test_credentials" {
  filename = "${path.module}/../tests/.credentials-${terraform.workspace}"

  file_permission = "0600"

  content = <<EOF
# THIS FILE IS GENERATED BY TERRAFORM, DO NOT EDIT
# Workspace: ${terraform.workspace}

# Test user access key for ${aws_iam_user.test_user.name}
export AWS_ACCESS_KEY_ID=${aws_iam_access_key.test_user.id}
export AWS_SECRET_ACCESS_KEY=${aws_iam_access_key.test_user.secret}

# DynamoDB table name
export TEST_DYNAMODB_TABLE=${aws_dynamodb_table.sensor_data.name}

# The base API url to hit
export TEST_BASE_URL=${aws_apigatewayv2_stage.prod.invoke_url}
EOF
}
